/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.8.0"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // You can declare any Maven/Ivy/file repository here.
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.2")

    implementation("org.jetbrains.kotlin:kotlin-script-runtime:1.8.0")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactive")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-slf4j")

    implementation("ch.qos.logback:logback-classic:1.4.1")

    implementation("org.slf4j:slf4j-api:2.0.3")

    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.4.0")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    testImplementation("io.mockk:mockk:1.12.2")
    testImplementation("io.kotest:kotest-property:5.6.2")
}

application {
    // Define the main class for the application.
    mainClass.set("quick.start.AppKt")
}
